# "version" atributi olib tashlandi
networks:
  analytic_net:
    driver: bridge

services:
  # 1. PostgreSQL ma'lumotlar bazasi
  postgres:
    image: postgres:15
    container_name: analytic_postgres
    env_file: .env
    networks:
      - analytic_net
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # 2. Redis kesh uchun
  redis:
    image: redis:7
    container_name: analytic_redis
    networks:
      - analytic_net
    ports:
      - "6379:6379"
    restart: unless-stopped
  
  # 3. Asosiy Bot
  bot:
    build: .
    container_name: analytic_bot
    env_file: .env
    depends_on:
      - postgres
      - redis
    networks:
      - analytic_net
    restart: unless-stopped
    command: python3 run_bot.py

  # 4. FastAPI Backend (TWA uchun)
  api:
    build: .
    container_name: analytic_api
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - analytic_net
    depends_on:
      - postgres
    restart: unless-stopped
    command: uvicorn api:app --host 0.0.0.0 --port 8000
  
  # 5. Celery Worker (Fon vazifalari uchun)
  celery_worker:
    build: .
    container_name: analytic_celery_worker
    env_file: .env
    depends_on:
      - redis
      - postgres
    networks:
      - analytic_net
    restart: unless-stopped
    command: celery -A src.bot.celery_app worker -l info

  # 6. Celery Beat (Vaqti-vaqti bilan ishlaydigan vazifalar uchun)
  celery_beat:
    build: .
    container_name: analytic_celery_beat
    env_file: .env
    depends_on:
      - redis
      - postgres
    networks:
      - analytic_net
    restart: unless-stopped
    command: celery -A src.bot.celery_app beat -l info
