services:
  postgres:
    image: postgres:16
    container_name: analyticbot_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: analyticuser
      POSTGRES_PASSWORD: analyticpass
      POSTGRES_DB: analyticbot_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: analyticbot_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
