name: Run Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Loyihangizdagi Python versiyasiga moslang

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # --- 3-TUZATISH START ---
    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies with Poetry
      run: |
        poetry install --no-root --without dev

    - name: Run tests with pytest
      run: |
        poetry run pytest